In [ ]:
export NAVER_CLIENT_ID="EGs26hVdRpcDBQxdTT80"

export NAVER_CLIENT_SECRET="EungL3NP4G"

In [13]:
import os
print(os.getenv("NAVER_CLIENT_ID"))

None

In [40]:
df4 = pd.read_parquet(r"D:\Desktop\AkiiiMonitor\data\raw\naver_shopping\naver_shopping_20260603.parquet")
df4

          period  keyword gender   age      ratio                collected_at
0     2022-12-26    아키클래식    all   all   71.35896  2026-06-03T16:13:22.028218
1     2023-01-02    아키클래식    all   all   63.77910  2026-06-03T16:13:22.028218
2     2023-01-09    아키클래식    all   all   55.87439  2026-06-03T16:13:22.028218
3     2023-01-16    아키클래식    all   all   43.69247  2026-06-03T16:13:22.028218
4     2023-01-23    아키클래식    all   all   81.42934  2026-06-03T16:13:22.028218
...          ...      ...    ...   ...        ...                         ...
2087  2024-11-04  컴포트수요지수      f   30s  100.00000  2026-06-03T16:13:22.028218
2088  2023-08-28  컴포트수요지수      f   40s  100.00000  2026-06-03T16:13:22.028218
2089  2023-12-04  컴포트수요지수      f   40s  100.00000  2026-06-03T16:13:22.028218
2090  2025-03-03  컴포트수요지수      f   50s  100.00000  2026-06-03T16:13:22.028218
2091  2023-05-01  컴포트수요지수      f  60s+  100.00000  2026-06-03T16:13:22.028218

[2092 rows x 6 columns]

In [44]:
df4[df4["keyword"] == '아키클래식']

          period keyword gender   age     ratio                collected_at
0     2022-12-26   아키클래식    all   all  71.35896  2026-06-03T16:13:22.028218
1     2023-01-02   아키클래식    all   all  63.77910  2026-06-03T16:13:22.028218
2     2023-01-09   아키클래식    all   all  55.87439  2026-06-03T16:13:22.028218
3     2023-01-16   아키클래식    all   all  43.69247  2026-06-03T16:13:22.028218
4     2023-01-23   아키클래식    all   all  81.42934  2026-06-03T16:13:22.028218
...          ...     ...    ...   ...       ...                         ...
2047  2025-10-27   아키클래식      f  60s+   0.86956  2026-06-03T16:13:22.028218
2048  2026-01-05   아키클래식      f  60s+   0.86956  2026-06-03T16:13:22.028218
2049  2026-04-06   아키클래식      f  60s+   0.86956  2026-06-03T16:13:22.028218
2050  2026-05-25   아키클래식      f  60s+   0.86956  2026-06-03T16:13:22.028218
2051  2026-06-01   아키클래식      f  60s+   0.86956  2026-06-03T16:13:22.028218

[2052 rows x 6 columns]

In [45]:
df4[df4["keyword"] == '여행시그널']

          period keyword gender  age  ratio                collected_at
2052  2024-03-25   여행시그널    all  all  100.0  2026-06-03T16:13:22.028218
2053  2025-10-13   여행시그널    all  all  100.0  2026-06-03T16:13:22.028218
2054  2024-03-25   여행시그널    all  20s  100.0  2026-06-03T16:13:22.028218
2055  2025-10-13   여행시그널    all  50s  100.0  2026-06-03T16:13:22.028218
2056  2024-03-25   여행시그널      m  all  100.0  2026-06-03T16:13:22.028218
2057  2025-10-13   여행시그널      m  all  100.0  2026-06-03T16:13:22.028218
2058  2024-03-25   여행시그널      m  20s  100.0  2026-06-03T16:13:22.028218
2059  2025-10-13   여행시그널      m  50s  100.0  2026-06-03T16:13:22.028218

In [46]:
df4[df4["keyword"] == '발건강시그널']

Empty DataFrame
Columns: [period, keyword, gender, age, ratio, collected_at]
Index: []

In [47]:
df4[df4["keyword"] == '컴포트수요지수']

          period  keyword gender   age      ratio                collected_at
2060  2023-05-01  컴포트수요지수    all   all   33.33333  2026-06-03T16:13:22.028218
2061  2023-05-15  컴포트수요지수    all   all   33.33333  2026-06-03T16:13:22.028218
2062  2023-08-28  컴포트수요지수    all   all   33.33333  2026-06-03T16:13:22.028218
2063  2023-09-11  컴포트수요지수    all   all   33.33333  2026-06-03T16:13:22.028218
2064  2023-12-04  컴포트수요지수    all   all   33.33333  2026-06-03T16:13:22.028218
2065  2024-07-08  컴포트수요지수    all   all   33.33333  2026-06-03T16:13:22.028218
2066  2024-11-04  컴포트수요지수    all   all   33.33333  2026-06-03T16:13:22.028218
2067  2025-03-03  컴포트수요지수    all   all  100.00000  2026-06-03T16:13:22.028218
2068  2023-09-11  컴포트수요지수    all   20s  100.00000  2026-06-03T16:13:22.028218
2069  2024-07-08  컴포트수요지수    all   30s  100.00000  2026-06-03T16:13:22.028218
2070  2024-11-04  컴포트수요지수    all   30s  100.00000  2026-06-03T16:13:22.028218
2071  2023-05-15  컴포트수요지수    all   40s  100.00000  2026-06-03T16:13:22.028218
2072  2023-08-28  컴포트수요지수    all   40s  100.00000  2026-06-03T16:13:22.028218
2073  2023-12-04  컴포트수요지수    all   40s  100.00000  2026-06-03T16:13:22.028218
2074  2025-03-03  컴포트수요지수    all   50s  100.00000  2026-06-03T16:13:22.028218
2075  2023-05-01  컴포트수요지수    all  60s+  100.00000  2026-06-03T16:13:22.028218
2076  2023-05-15  컴포트수요지수      m   all  100.00000  2026-06-03T16:13:22.028218
2077  2023-05-15  컴포트수요지수      m   40s  100.00000  2026-06-03T16:13:22.028218
2078  2023-05-01  컴포트수요지수      f   all   33.33333  2026-06-03T16:13:22.028218
2079  2023-08-28  컴포트수요지수      f   all   33.33333  2026-06-03T16:13:22.028218
2080  2023-09-11  컴포트수요지수      f   all   33.33333  2026-06-03T16:13:22.028218
2081  2023-12-04  컴포트수요지수      f   all   33.33333  2026-06-03T16:13:22.028218
2082  2024-07-08  컴포트수요지수      f   all   33.33333  2026-06-03T16:13:22.028218
2083  2024-11-04  컴포트수요지수      f   all   33.33333  2026-06-03T16:13:22.028218
2084  2025-03-03  컴포트수요지수      f   all  100.00000  2026-06-03T16:13:22.028218
2085  2023-09-11  컴포트수요지수      f   20s  100.00000  2026-06-03T16:13:22.028218
2086  2024-07-08  컴포트수요지수      f   30s  100.00000  2026-06-03T16:13:22.028218
2087  2024-11-04  컴포트수요지수      f   30s  100.00000  2026-06-03T16:13:22.028218
2088  2023-08-28  컴포트수요지수      f   40s  100.00000  2026-06-03T16:13:22.028218
2089  2023-12-04  컴포트수요지수      f   40s  100.00000  2026-06-03T16:13:22.028218
2090  2025-03-03  컴포트수요지수      f   50s  100.00000  2026-06-03T16:13:22.028218
2091  2023-05-01  컴포트수요지수      f  60s+  100.00000  2026-06-03T16:13:22.028218

In [38]:
df4[df4["ratio"] == 100]

          period  keyword gender   age  ratio                collected_at
14    2023-04-03    아키클래식    all   all  100.0  2026-06-03T16:13:22.028218
168   2023-03-27    아키클래식    all   10s  100.0  2026-06-03T16:13:22.028218
193   2023-02-06    아키클래식    all   20s  100.0  2026-06-03T16:13:22.028218
283   2023-03-20    아키클래식    all   30s  100.0  2026-06-03T16:13:22.028218
407   2023-04-03    아키클래식    all   40s  100.0  2026-06-03T16:13:22.028218
547   2023-02-27    아키클래식    all   50s  100.0  2026-06-03T16:13:22.028218
682   2023-01-23    아키클래식    all  60s+  100.0  2026-06-03T16:13:22.028218
804   2023-03-20    아키클래식      m   all  100.0  2026-06-03T16:13:22.028218
906   2023-04-03    아키클래식      m   10s  100.0  2026-06-03T16:13:22.028218
919   2023-02-20    아키클래식      m   20s  100.0  2026-06-03T16:13:22.028218
971   2023-03-20    아키클래식      m   30s  100.0  2026-06-03T16:13:22.028218
1053  2023-03-20    아키클래식      m   40s  100.0  2026-06-03T16:13:22.028218
1150  2023-02-06    아키클래식      m   50s  100.0  2026-06-03T16:13:22.028218
1156  2023-03-20    아키클래식      m   50s  100.0  2026-06-03T16:13:22.028218
1232  2022-12-26    아키클래식      m  60s+  100.0  2026-06-03T16:13:22.028218
1294  2023-03-20    아키클래식      f   all  100.0  2026-06-03T16:13:22.028218
1446  2023-03-27    아키클래식      f   10s  100.0  2026-06-03T16:13:22.028218
1468  2023-02-06    아키클래식      f   20s  100.0  2026-06-03T16:13:22.028218
1550  2023-03-20    아키클래식      f   30s  100.0  2026-06-03T16:13:22.028218
1674  2023-04-03    아키클래식      f   40s  100.0  2026-06-03T16:13:22.028218
1809  2023-02-27    아키클래식      f   50s  100.0  2026-06-03T16:13:22.028218
1943  2023-01-23    아키클래식      f  60s+  100.0  2026-06-03T16:13:22.028218
2052  2024-03-25    여행시그널    all   all  100.0  2026-06-03T16:13:22.028218
2053  2025-10-13    여행시그널    all   all  100.0  2026-06-03T16:13:22.028218
2054  2024-03-25    여행시그널    all   20s  100.0  2026-06-03T16:13:22.028218
2055  2025-10-13    여행시그널    all   50s  100.0  2026-06-03T16:13:22.028218
2056  2024-03-25    여행시그널      m   all  100.0  2026-06-03T16:13:22.028218
2057  2025-10-13    여행시그널      m   all  100.0  2026-06-03T16:13:22.028218
2058  2024-03-25    여행시그널      m   20s  100.0  2026-06-03T16:13:22.028218
2059  2025-10-13    여행시그널      m   50s  100.0  2026-06-03T16:13:22.028218
2067  2025-03-03  컴포트수요지수    all   all  100.0  2026-06-03T16:13:22.028218
2068  2023-09-11  컴포트수요지수    all   20s  100.0  2026-06-03T16:13:22.028218
2069  2024-07-08  컴포트수요지수    all   30s  100.0  2026-06-03T16:13:22.028218
2070  2024-11-04  컴포트수요지수    all   30s  100.0  2026-06-03T16:13:22.028218
2071  2023-05-15  컴포트수요지수    all   40s  100.0  2026-06-03T16:13:22.028218
2072  2023-08-28  컴포트수요지수    all   40s  100.0  2026-06-03T16:13:22.028218
2073  2023-12-04  컴포트수요지수    all   40s  100.0  2026-06-03T16:13:22.028218
2074  2025-03-03  컴포트수요지수    all   50s  100.0  2026-06-03T16:13:22.028218
2075  2023-05-01  컴포트수요지수    all  60s+  100.0  2026-06-03T16:13:22.028218
2076  2023-05-15  컴포트수요지수      m   all  100.0  2026-06-03T16:13:22.028218
2077  2023-05-15  컴포트수요지수      m   40s  100.0  2026-06-03T16:13:22.028218
2084  2025-03-03  컴포트수요지수      f   all  100.0  2026-06-03T16:13:22.028218
2085  2023-09-11  컴포트수요지수      f   20s  100.0  2026-06-03T16:13:22.028218
2086  2024-07-08  컴포트수요지수      f   30s  100.0  2026-06-03T16:13:22.028218
2087  2024-11-04  컴포트수요지수      f   30s  100.0  2026-06-03T16:13:22.028218
2088  2023-08-28  컴포트수요지수      f   40s  100.0  2026-06-03T16:13:22.028218
2089  2023-12-04  컴포트수요지수      f   40s  100.0  2026-06-03T16:13:22.028218
2090  2025-03-03  컴포트수요지수      f   50s  100.0  2026-06-03T16:13:22.028218
2091  2023-05-01  컴포트수요지수      f  60s+  100.0  2026-06-03T16:13:22.028218

In [19]:
df3 = pd.read_parquet(r"D:\Desktop\AkiiiMonitor\data\raw\google_trends\google_trends_20260602.parquet")
df3

         period keyword  ratio                collected_at
0    2025-06-01   아키클래식      0  2026-06-02T13:50:07.285746
1    2025-06-01    버켄스탁     16  2026-06-02T13:50:07.285746
2    2025-06-01     크록스     69  2026-06-02T13:50:07.285746
3    2025-06-01    컴포트화      0  2026-06-02T13:50:07.285746
4    2025-06-08   아키클래식      0  2026-06-02T13:50:07.285746
..          ...     ...    ...                         ...
203  2026-05-17    컴포트화      0  2026-06-02T13:50:07.285746
204  2026-05-24   아키클래식      3  2026-06-02T13:50:07.285746
205  2026-05-24    버켄스탁     11  2026-06-02T13:50:07.285746
206  2026-05-24     크록스     66  2026-06-02T13:50:07.285746
207  2026-05-24    컴포트화      1  2026-06-02T13:50:07.285746

[208 rows x 4 columns]

In [22]:
df2 = pd.read_parquet(r"D:\Desktop\AkiiiMonitor\data\raw\naver_search\naver_search_20260602.parquet")
df2

  keyword  blog_total  news_total                collected_at
0   아키클래식       19771        5587  2026-06-02T13:52:35.976102
1    버켄스탁       75201        4019  2026-06-02T13:52:36.160193
2     크록스      605416       19425  2026-06-02T13:52:36.294390
3    컴포트화       10092        2983  2026-06-02T13:52:36.452477

In [1]:
import pandas as pd
df = pd.read_parquet(r"D:\Desktop\AkiiiMonitor\data\raw\naver_datalab\naver_datalab_20260602.parquet")
df

          period keyword_group    axis     ratio                collected_at
0     2022-12-26         아키클래식  direct  44.68168  2026-06-02T17:38:41.585043
1     2023-01-02         아키클래식  direct  41.35908  2026-06-02T17:38:41.585043
2     2023-01-09         아키클래식  direct  39.62088  2026-06-02T17:38:41.585043
3     2023-01-16         아키클래식  direct  38.21888  2026-06-02T17:38:41.585043
4     2023-01-23         아키클래식  direct  57.51788  2026-06-02T17:38:41.585043
...          ...           ...     ...       ...                         ...
1795  2026-05-04        발건강시그널  market  29.07367  2026-06-02T17:38:41.585043
1796  2026-05-11        발건강시그널  market  28.22246  2026-06-02T17:38:41.585043
1797  2026-05-18        발건강시그널  market  27.78969  2026-06-02T17:38:41.585043
1798  2026-05-25        발건강시그널  market  26.12303  2026-06-02T17:38:41.585043
1799  2026-06-01        발건강시그널  market   4.06652  2026-06-02T17:38:41.585043

[1800 rows x 5 columns]

In [4]:
from collectors.naver_shopping import NaverShoppingCollector
import json

collector = NaverShoppingCollector(
        client_id="EGs26hVdRpcDBQxdTT80",
        client_secret="5PIziAaWiC",
    )

raw = collector.fetch_keyword_trend(
    category="50000167",
    keywords=[{"name": "아키클래식", "param": ["아키클래식"]}],
    gender="f",
    time_unit="week",
)
print(json.dumps(raw, ensure_ascii=False, indent=2))

{
  "startDate": "2025-05-26",
  "endDate": "2026-06-03",
  "timeUnit": "week",
  "results": [
    {
      "title": "아키클래식",
      "keyword": [
        "아키클래식"
      ],
      "data": [
        {
          "period": "2025-05-26",
          "ratio": 100
        },
        {
          "period": "2025-06-02",
          "ratio": 12.5
        },
        {
          "period": "2025-06-09",
          "ratio": 6.25
        },
        {
          "period": "2025-06-16",
          "ratio": 12.5
        },
        {
          "period": "2025-06-23",
          "ratio": 12.5
        },
        {
          "period": "2025-07-14",
          "ratio": 12.5
        },
        {
          "period": "2025-08-04",
          "ratio": 18.75
        },
        {
          "period": "2025-09-01",
          "ratio": 18.75
        },
        {
          "period": "2025-09-08",
          "ratio": 12.5
        },
        {
          "period": "2025-09-29",
          "ratio": 31.25
        },
        {
          "period": "2025-10-27",
          "ratio": 25
        },
        {
          "period": "2025-11-03",
          "ratio": 12.5
        },
        {
          "period": "2025-11-24",
          "ratio": 6.25
        },
        {
          "period": "2025-12-08",
          "ratio": 18.75
        },
        {
          "period": "2026-01-05",
          "ratio": 6.25
        },
        {
          "period": "2026-01-12",
          "ratio": 6.25
        },
        {
          "period": "2026-02-09",
          "ratio": 6.25
        },
        {
          "period": "2026-02-16",
          "ratio": 6.25
        },
        {
          "period": "2026-02-23",
          "ratio": 6.25
        },
        {
          "period": "2026-03-02",
          "ratio": 12.5
        },
        {
          "period": "2026-03-23",
          "ratio": 12.5
        },
        {
          "period": "2026-04-06",
          "ratio": 6.25
        },
        {
          "period": "2026-04-13",
          "ratio": 6.25
        },
        {
          "period": "2026-04-20",
          "ratio": 12.5
        },
        {
          "period": "2026-05-04",
          "ratio": 12.5
        },
        {
          "period": "2026-05-11",
          "ratio": 18.75
        },
        {
          "period": "2026-05-18",
          "ratio": 12.5
        },
        {
          "period": "2026-05-25",
          "ratio": 6.25
        },
        {
          "period": "2026-06-01",
          "ratio": 6.25
        }
      ]
    }
  ]
}

In [14]:
# param 여러 개 테스트
response = requests.post(
    "https://openapi.naver.com/v1/datalab/shopping/category/keywords",
    headers=headers,
    data=json.dumps({
        "startDate": "2023-01-01",
        "endDate": "2026-06-03",
        "timeUnit": "week",
        "category": "50000167",
        "keyword": [
            {"name": "여행시그널", "param": ["여행 운동화", "여행운동화", "여행용 운동화"]},
        ],
        "device": "",
        "gender": "",
        "ages": []
    }, ensure_ascii=False).encode('utf-8')
)
print(response.status_code)
print(json.dumps(response.json(), ensure_ascii=False, indent=2))

400
{
  "errMsg": "TypeError: .keyword[0].param -> should NOT have more than 1 items",
  "errId": "2026-06-03T13:54:04+09:00/479326731-879639852",
  "body": "{\"startDate\":\"2023-01-01\",\"endDate\":\"2026-06-03\",\"timeUnit\":\"week\",\"category\":\"50000167\",\"keyword\":[{\"name\":\"여행시그널\",\"param\":[\"여행 운동화\",\"여행운동화\",\"여행용 운동화\"]}],\"device\":\"\",\"gender\":\"\",\"ages\":[]}"
}

In [15]:
response = requests.post(
    "https://openapi.naver.com/v1/datalab/shopping/category/keywords",
    headers=headers,
    data=json.dumps({
        "startDate": "2023-01-01",
        "endDate": "2026-06-03",
        "timeUnit": "week",
        "category": "50000167",
        "keyword": [
            {"name": "여행시그널", "param": ["여행 운동화"]},
            {"name": "발건강시그널", "param": ["족저근막염"]},
        ],
        "device": "",
        "gender": "",
        "ages": []
    }, ensure_ascii=False).encode('utf-8')
)
print(response.status_code)
print(json.dumps(response.json(), ensure_ascii=False, indent=2))

200
{
  "startDate": "2022-12-26",
  "endDate": "2026-06-03",
  "timeUnit": "week",
  "results": [
    {
      "title": "여행시그널",
      "keyword": [
        "여행운동화"
      ],
      "data": [
        {
          "period": "2023-12-11",
          "ratio": 100
        }
      ]
    },
    {
      "title": "발건강시그널",
      "keyword": [
        "족저근막염"
      ],
      "data": [
        {
          "period": "2024-12-02",
          "ratio": 100
        }
      ]
    }
  ]
}

In [12]:
import requests
import json

headers = {
    "X-Naver-Client-Id": "EGs26hVdRpcDBQxdTT80",
    "X-Naver-Client-Secret": "5PIziAaWiC",
    "Content-Type": "application/json",
}

# market 그룹 4개 한번에 테스트
response = requests.post(
    "https://openapi.naver.com/v1/datalab/shopping/category/keywords",
    headers=headers,
    json={
        "startDate": "2023-01-01",
        "endDate": "2026-06-03",
        "timeUnit": "week",
        "category": "50000167",
        "keyword": [
            {"name": "아키클래식", "param": ["아키클래식", "AKIII", "AKIII CLASSIC", "아키 클래식"]},
            {"name": "컴포트수요지수", "param": ["편한 운동화", "발 편한 신발", "편한 신발", "컴포트화", "워킹화", "경량 운동화"]},
            {"name": "여행시그널", "param": ["여행 운동화", "여행운동화", "여행용 운동화", "트레킹화", "트래킹화"]},
            {"name": "발건강시그널", "param": ["족저근막염 운동화", "족저근막 운동화", "족저근막염 신발", "아치서포트", "발건강 운동화", "발 건강 신발"]},
        ],
        "device": "",
        "gender": "",
        "ages": []
    }
)

print(response.status_code)
print(json.dumps(response.json(), ensure_ascii=False, indent=2))

400
{
  "errMsg": "TypeError: .keyword[0].param -> should NOT have more than 1 items",
  "errId": "2026-06-03T11:10:14+09:00/896224660-134994346",
  "body": "{\"startDate\":\"2023-01-01\",\"endDate\":\"2026-06-03\",\"timeUnit\":\"week\",\"category\":\"50000167\",\"keyword\":[{\"name\":\"아키클래식\",\"param\":[\"아키클래식\",\"AKIII\",\"AKIII CLASSIC\",\"아키 클래식\"]},{\"name\":\"컴포트수요지수\",\"param\":[\"편한 운동화\",\"발 편한 신발\",\"편한 신발\",\"컴포트화\",\"워킹화\",\"경량 운동화\"]},{\"name\":\"여행시그널\",\"param\":[\"여행 운동화\",\"여행운동화\",\"여행용 운동화\",\"트레킹화\",\"트래킹화\"]},{\"name\":\"발건강시그널\",\"param\":[\"족저근막염 운동화\",\"족저근막 운동화\",\"족저근막염 신발\",\"아치서포트\",\"발건강 운동화\",\"발 건강 신발\"]}],\"device\":\"\",\"gender\":\"\",\"ages\":[]}"
}

In [24]:
import json
import requests

headers = {
    "X-Naver-Client-Id": "EGs26hVdRpcDBQxdTT80",
    "X-Naver-Client-Secret": "EungL3NP4G",
    "Content-Type": "application/json",
}

# 카테고리 없이 버켄스탁만 조회
response = requests.post(
    "https://openapi.naver.com/v1/datalab/shopping/category/keywords",
    headers=headers,
    json={
        "startDate": "2025-06-01",
        "endDate": "2026-06-01",
        "timeUnit": "week",
        "category": "50000000",  # 패션의류 상위 카테고리
        "keyword": [
            {"name": "버켄스탁", "param": ["버켄스탁"]},
            {"name": "크록스", "param": ["크록스"]},
        ],
        "device": "",
        "gender": "",
        "ages": []
    }
)
print(json.dumps(response.json(), ensure_ascii=False, indent=2))

{
  "errorMessage": "NID AUTH Result Invalid (28) : Authentication failed. (인증에 실패했습니다.)",
  "errorCode": "024"
}

In [11]:
from pytrends.request import TrendReq
import json

pytrends = TrendReq(hl='ko', tz=540)  # 한국 시간대

pytrends.build_payload(
    kw_list=["아키클래식", "버켄스탁", "크록스"],
    timeframe="today 12-m",  # 최근 1년
    geo="KR"  # 한국
)

df = pytrends.interest_over_time()
print(df)

            아키클래식  버켄스탁  크록스  isPartial
date
2025-06-01      0    16   69      False
2025-06-08      0    15   82      False
2025-06-15      0    14   85      False
2025-06-22      3    16   79      False
2025-06-29      0    10   79      False
2025-07-06      4    13  100      False
2025-07-13      0    13   99      False
2025-07-20      4    13   92      False
2025-07-27      0    10   95      False
2025-08-03      0    12   84      False
2025-08-10      0    12   66      False
2025-08-17      4     6   65      False
2025-08-24      0     8   64      False
2025-08-31      0     6   59      False
2025-09-07      0     8   51      False
2025-09-14      0     9   48      False
2025-09-21      3     9   52      False
2025-09-28      5    10   41      False
2025-10-05      0     6   43      False
2025-10-12      0     7   48      False
2025-10-19      0     6   48      False
2025-10-26      5     6   40      False
2025-11-02      3     7   38      False
2025-11-09      6     6   42      False
2025-11-16      6     4   54      False
2025-11-23      0     7   43      False
2025-11-30      0     6   49      False
2025-12-07      5     5   41      False
2025-12-14      0     4   37      False
2025-12-21      4     5   41      False
2025-12-28      0     5   35      False
2026-01-04     12     7   32      False
2026-01-11      8     7   26      False
2026-01-18      6     6   33      False
2026-01-25      4     4   33      False
2026-02-01      5     6   30      False
2026-02-08      4     0   28      False
2026-02-15      4     7   34      False
2026-02-22      4     6   40      False
2026-03-01      5     8   44      False
2026-03-08      5     7   40      False
2026-03-15      6     7   41      False
2026-03-22      4     9   40      False
2026-03-29      6     7   45      False
2026-04-05      5     6   43      False
2026-04-12      0     9   49      False
2026-04-19      6     9   53      False
2026-04-26      4     8   52      False
2026-05-03      4     8   63      False
2026-05-10      4     8   59      False
2026-05-17      3    13   67      False
2026-05-24      3    11   66      False
2026-05-31      3    17   74       True

c:\Users\ugc05\AppData\Local\Programs\Python\Python313\Lib\site-packages\pytrends\request.py:260: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.fillna(False)

In [3]:
import os
import pandas as pd
from naver_datalab import NaverDataLabCollector

collector = NaverDataLabCollector(
    client_id="EGs26hVdRpcDBQxdTT80",
    client_secret="EungL3NP4G",
)

raw = collector.fetch_archi_vs_market()
rows = collector.parse_to_rows(raw)

df = pd.DataFrame(rows)
df["period"] = pd.to_datetime(df["period"])
df = df.sort_values("period")

df

        period keyword_group     ratio                collected_at
0   2025-06-02         아키클래식   5.94992  2026-06-02T10:42:40.951255
53  2025-06-02        컴포트화시장   3.38120  2026-06-02T10:42:40.951255
106 2025-06-02         경쟁브랜드  86.76186  2026-06-02T10:42:40.951255
1   2025-06-09         아키클래식   6.00544  2026-06-02T10:42:40.951255
54  2025-06-09        컴포트화시장   3.61476  2026-06-02T10:42:40.951255
..         ...           ...       ...                         ...
51  2026-05-25         아키클래식   4.96930  2026-06-02T10:42:40.951255
104 2026-05-25        컴포트화시장   3.08539  2026-06-02T10:42:40.951255
105 2026-06-01        컴포트화시장   0.48654  2026-06-02T10:42:40.951255
52  2026-06-01         아키클래식   0.75063  2026-06-02T10:42:40.951255
158 2026-06-01         경쟁브랜드  11.39348  2026-06-02T10:42:40.951255

[159 rows x 4 columns]

In [52]:
import sys
sys.path.append(r"D:\Desktop\AkiiiMonitor\collectors")

import json
import requests
from naver_search import NaverSearchCollector

collector = NaverSearchCollector(
    client_id="EGs26hVdRpcDBQxdTT80",
    client_secret="5PIziAaWiC",
)

URLS = {
    "블로그": "https://openapi.naver.com/v1/search/blog.json",
    "뉴스":   "https://openapi.naver.com/v1/search/news.json",
    "카페":   "https://openapi.naver.com/v1/search/cafearticle.json",
}

for name, url in URLS.items():
    response = requests.get(
        url,
        headers=collector.headers,
        params={"query": "아키클래식", "display": 3, "sort": "date"}
    )
    print(f"\n{'='*20} {name} {'='*20}")
    print(json.dumps(response.json(), ensure_ascii=False, indent=2))

==================== 블로그 ====================
{
  "lastBuildDate": "Wed, 03 Jun 2026 16:31:50 +0900",
  "total": 19767,
  "start": 1,
  "display": 3,
  "items": [
    {
      "title": "<b>아키클래식</b> 듀얼 쿠셔닝 그라나다 샌들, 1주 착용 후기",
      "link": "https://blog.naver.com/shopping99z/224304086954",
      "description": "여름이 다가오면서 어떤 신발을 신을지 고민하다가 <b>아키클래식</b> 샌들을 골라봤어요. 많은 분들이... 구매 전 확인해보기  https://naver.me/xJccPhhN #<b>아키클래식</b> #<b>아키클래식</b>샌들 #그라나다샌들 #여름샌들 #여자샌들... ",
      "bloggername": "쇼핑천국",
      "bloggerlink": "blog.naver.com/shopping99z",
      "postdate": "20260603"
    },
    {
      "title": "[공연 소개] 부산<b>클래식</b>연주회, 지브리영화음악콘서트, 6월... ",
      "link": "https://blog.naver.com/stagem1/224304037491",
      "description": "안녕하세요, 전국에 <b>클래식</b>의 감미로운 선율과 감동을 전하는 공연제작사 스테이지엠 입니다.... 부산 근교 양산과 울산에서도 스테이지엠이 특별한 공연을 준비했습니다  아즈마 <b>아키</b>와 함께하는 영화음악... ",
      "bloggername": "트렌디한 클래식 공연문화를 만들어가는 스테이지M",
      "bloggerlink": "blog.naver.com/stagem1",
      "postdate": "20260603"
    },
    {
      "title": "[<b>아키클래식</b>] 하이마일즈 가격 체감과 후기",
      "link": "https://blog.naver.com/ctlogue74085/224304546533",
      "description": "[<b>아키클래식</b>] 하이마일즈 가격 체감과 후기 하이마일즈 구매 후 느낀 점 하이마일즈는 디자인이... #하이마일즈 #<b>아키클래식</b> #리뷰 #사용기 #스니커즈 #패션 #할인 #편안함 #디자인 #구매 #쇼핑 #추천 #고민... ",
      "bloggername": "ctlogue74085님의 블로그",
      "bloggerlink": "blog.naver.com/ctlogue74085",
      "postdate": "20260603"
    }
  ]
}

==================== 뉴스 ====================
{
  "lastBuildDate": "Wed, 03 Jun 2026 16:31:50 +0900",
  "total": 5587,
  "start": 1,
  "display": 3,
  "items": [
    {
      "title": "주수빈 4타차 선두…LPGA투어 첫 우승 꿈에 한발짝",
      "originallink": "https://www.mk.co.kr/article/12062055",
      "link": "https://m.sports.naver.com/golf/article/009/0005687299",
      "description": "중간합계 8언더파 134타를 기록한 주수빈은 이소미, 이와이 치지(일본), 이와이 <b>아키</b>(일본), 셀린 부티에... 2023년 데뷔 첫해 출전한 이 대회 (당시 숍라이트 LPGA <b>클래식</b>)에서 공동 6위에 올랐다. 주수빈이 기록한... ",
      "pubDate": "Sun, 31 May 2026 12:08:00 +0900"
    },
    {
      "title": "‘개인 최고 성적’ 거뒀던 숍라이트 LPGA서 데뷔 첫 승 눈앞에 둔 주수...",
      "originallink": "https://sports.donga.com/sports/article/all/20260531/134021753/1",
      "link": "https://m.sports.naver.com/golf/article/382/0001276031",
      "description": "LPGA <b>클래식</b>으로 불렸던 이 대회에서 역대 개인 최고인 공동 6위를 기록했다. 2위 그룹에는 이소미와 함께 1라운드 선두였던 레티시아 베크(이스라엘), 일본의 쌍둥이 자매인 이와이 지지와 이와이 <b>아키</b>, 2021년 이... ",
      "pubDate": "Sun, 31 May 2026 10:17:00 +0900"
    },
    {
      "title": "주수빈, 숍라이트 LPGA 2R 단독 선두…이소미 포함된 2위 그룹과 4타 차",
      "originallink": "http://www.stoo.com/article.php?aid=106926274654",
      "link": "http://www.stoo.com/article.php?aid=106926274654",
      "description": "이와이 <b>아키</b>(이상 일본), 셀린 부티에(프랑스), 라에티샤 벡(이스라엘)와는 4타 차다. 2023년 LPGA 투어에 데뷔한 주수빈은 아직 우승을 차지하지 못했다. 2023년 6월 숍라이트 <b>클래식</b>에서 공동 6위에 오른 것이 개인 최고... ",
      "pubDate": "Sun, 31 May 2026 10:08:00 +0900"
    }
  ]
}

==================== 카페 ====================
{
  "lastBuildDate": "Wed, 03 Jun 2026 16:31:50 +0900",
  "total": 9820,
  "start": 1,
  "display": 3,
  "items": [
    {
      "title": "<b>아키클래식</b> 부메랑 키높이 운동화 230사이즈 새제품",
      "link": "http://cafe.naver.com/joonggonara/1130264252",
      "description": "7 장 이미지 더보기 〉 상품 정보 <b>아키클래식</b> 부메랑 키높이 운동화 230사이즈 새제품 35,000원 시세조회 결제 혜택 N - 상품 상태 새상품, 구성품 전체 거래 방법 직거래, 택배거래 거래 희망지역 연수2동 판매자 정보... ",
      "cafename": "중고나라",
      "cafeurl": "https://cafe.naver.com/joonggonara"
    },
    {
      "title": "운동화 245",
      "link": "http://cafe.naver.com/joonggonara/1130261765",
      "description": "상세 <b>아키클래식</b> 등산화/트레킹화입니다. 신상이라 디자인도 너무 예쁘고, 트레킹할때 신으면 착화감도 엄청 좋을 것 같아요. 사이즈 좀 작아서 실착 2회후 판매합니다 260~265추천 평소에 운동화로 활용해도 예쁠... ",
      "cafename": "중고나라",
      "cafeurl": "https://cafe.naver.com/joonggonara"
    },
    {
      "title": "<b>아키클래식</b> 요세미티 트래커 V2 벨크로 샌들, 지금이 기회예요!",
      "link": "http://cafe.naver.com/maplestorycafe1099/21023",
      "description": "[<b>아키클래식</b>] 요세미티 트래커 V2 벨크로 키높이 샌들 두개 구매 시 자동 추가할인 구입시 네이버 브랜드 커넥트 활동에 따라 일정액의 수수료를 받습니다. 여름이 다가오면서 신발 고르는 고민, 다들 하셨죠? 저는 매번... ",
      "cafename": "메이플스토리qp캣츠qp카페",
      "cafeurl": "https://cafe.naver.com/maplestorycafe1099"
    }
  ]
}