In [ ]:
export NAVER_CLIENT_ID="EGs26hVdRpcDBQxdTT80"

export NAVER_CLIENT_SECRET="EungL3NP4G"

In [13]:
import os
print(os.getenv("NAVER_CLIENT_ID"))

None

In [4]:
import pandas as pd

In [6]:
mb.shape

(300, 7)

In [8]:
mt = pd.read_parquet(r"D:\Desktop\AkiiiMonitor\data\raw\mention_total\mention_total_20260604.parquet")
mt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   keyword       3 non-null      object
 1   blog_total    3 non-null      int64
 2   news_total    3 non-null      int64
 3   cafe_total    3 non-null      int64
 4   collected_at  3 non-null      object
dtypes: int64(3), object(2)
memory usage: 252.0+ bytes

In [17]:
mt.head(3)

  keyword  blog_total  news_total  cafe_total                collected_at
0   아키클래식       13118        4398        7165  2026-06-04T11:20:17.437552
1    포즈간츠        1702         238         527  2026-06-04T11:20:17.437552
2   23.65        7046        2738        4019  2026-06-04T11:20:17.437552

In [10]:
mc = pd.read_parquet(r"D:\Desktop\AkiiiMonitor\data\raw\mention_cafe\mention_cafe_20260604.parquet")
mc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2527 entries, 0 to 2526
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   keyword       2527 non-null   object
 1   title         2527 non-null   object
 2   description   2527 non-null   object
 3   cafename      2527 non-null   object
 4   cafeurl       2527 non-null   object
 5   link          2527 non-null   object
 6   collected_at  2527 non-null   object
dtypes: object(7)
memory usage: 138.3+ KB

In [18]:
mc.head(3)

,keyword,title,description,cafename,cafeurl,link,collected_at
0,아키클래식,<b>아키클래식</b> 아치-핏 폼 플립플랍 <b>아키클래식</b> 여성 신발 후기,<b>아키클래식</b> 아치-핏 폼 플립플랍 <b>아키클래식</b> 여성 신발 후기...,작가모임♡,https://cafe.naver.com/gjsdlf1234,http://cafe.naver.com/gjsdlf1234/770,2026-06-04T11:20:17.437552
1,아키클래식,<b>아키클래식</b> 부메랑 키높이 운동화 230사이즈 새제품,7 장 이미지 더보기 〉 상품 정보 <b>아키클래식</b> 부메랑 키높이 운동화 2...,중고나라,https://cafe.naver.com/joonggonara,http://cafe.naver.com/joonggonara/1130264252,2026-06-04T11:20:17.437552
2,아키클래식,운동화 245,"상세 <b>아키클래식</b> 등산화/트레킹화입니다. 신상이라 디자인도 너무 예쁘고,...",중고나라,https://cafe.naver.com/joonggonara,http://cafe.naver.com/joonggonara/1130261765,2026-06-04T11:20:17.437552

In [11]:
mn = pd.read_parquet(r"D:\Desktop\AkiiiMonitor\data\raw\mention_news\mention_news_20260604.parquet")
mn.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2238 entries, 0 to 2237
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   keyword       2238 non-null   object
 1   title         2238 non-null   object
 2   description   2238 non-null   object
 3   originallink  2238 non-null   object
 4   pub_date      2238 non-null   object
 5   link          2238 non-null   object
 6   collected_at  2238 non-null   object
dtypes: object(7)
memory usage: 122.5+ KB

In [19]:
mn.head(2)

,keyword,title,description,originallink,pub_date,link,collected_at
0,아키클래식,"<b>아키클래식</b>, '썸머 블랙프라이데이’ 진행",올위메이크이즈(대표 남수안)의 라이프스타일 스포츠 브랜드 ‘<b>아키클래식</b>’...,http://www.apparelnews.co.kr/news/news_view/?i...,"Thu, 04 Jun 2026 09:38:00 +0900",http://www.apparelnews.co.kr/news/news_view/?i...,2026-06-04T11:20:17.437552
1,아키클래식,"<b>아키클래식</b>, 중국 ‘티몰 글로벌’ 입점",올위메이크이즈(대표 남수안)의 라이프스타일 스포츠 브랜드 ‘<b>아키클래식</b>’...,http://www.apparelnews.co.kr/news/news_view/?i...,"Wed, 20 May 2026 14:28:00 +0900",http://www.apparelnews.co.kr/news/news_view/?i...,2026-06-04T11:20:17.437552

In [12]:
mb = pd.read_parquet(r"D:\Desktop\AkiiiMonitor\data\raw\mention_blog\mention_blog_20260604.parquet")
mb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   keyword       3000 non-null   object
 1   title         3000 non-null   object
 2   description   3000 non-null   object
 3   bloggername   3000 non-null   object
 4   postdate      3000 non-null   object
 5   link          3000 non-null   object
 6   collected_at  3000 non-null   object
dtypes: object(7)
memory usage: 164.2+ KB

In [20]:
mb.head(2)

,keyword,title,description,bloggername,postdate,link,collected_at
0,아키클래식,<b>아키클래식</b> 프리워크 발 편한 운동화 직접 신어보니,<b>아키클래식</b> 프리워크 발 편한 운동화 직접 신어보니 <b>아키클래식</b...,hnded60979님의 블로그,20260604,https://blog.naver.com/hnded60979/224305503816,2026-06-04T11:20:17.437552
1,아키클래식,[<b>아키클래식</b>] 발 편한 운동화 프리워크 두개 구매시 자동 추가...,[<b>아키클래식</b>] 발 편한 운동화 프리워크 두개 구매시 자동 추가 할인 [...,tqil71666님의 블로그,20260604,https://blog.naver.com/tqil71666/224305501518,2026-06-04T11:20:17.437552

In [29]:
mb[mb['keyword'] == '아키클래식'].tail(10)

,keyword,title,description,bloggername,postdate,link,collected_at
990,아키클래식,"발 편한 운동화, 합리적 가격으로 만나기",브랜드: <b>아키클래식</b> 운동화를 고를 때 보면 기준이 사람마다 꽤 달라요....,bncsomewhere님의 블로그,20260413,https://blog.naver.com/bncsomewhere/224250193267,2026-06-04T11:20:17.437552
991,아키클래식,발 편안함을 선사하는 <b>아키클래식</b> 범퍼 트레이너의 매력,<b>아키클래식</b>의 발 편한 운동화인 범퍼 트레이너는 이러한 요구를 충족시키기...,고구마연구소,20260413,https://blog.naver.com/liwe8wq/224250166234,2026-06-04T11:20:17.437552
992,아키클래식,<b>아키클래식</b> 발 편한 운동화 범퍼 트레이너 2개 구매 시 자동...,아래 링크 참고 두개구매추가할인확인하기 확인하기 <b>아키클래식</b> 발 편한 운...,unemployed8q님의 블로그,20260413,https://blog.naver.com/unemployed8q/224250163639,2026-06-04T11:20:17.437552
993,아키클래식,"발 편안함과 디자인을 동시에, <b>아키클래식</b> 운동화 리뷰",브랜드: <b>아키클래식</b> 도입부 운동화를 고르다 보면 착화감이 가장 먼저 궁...,nuhyzk님의 블로그,20260413,https://blog.naver.com/nuhyzk/224250162967,2026-06-04T11:20:17.437552
994,아키클래식,"<b>아키클래식</b> 발 편한 운동화, 2개 구매 시 추가 할인 정보",브랜드: <b>아키클래식</b> 새 운동화를 고르려고 하면 생각보다 준비할 게 많아...,웨청의 희얼사 드라마 블로그,20260413,https://blog.naver.com/vytyrl42c0eo/224250161541,2026-06-04T11:20:17.437552
995,아키클래식,나이키 운동화 선택 시 고려할 3가지 필수 기능,브랜드: <b>아키클래식</b> 운동화 구매를 고민하는 분들 많죠? 특히 나이키 운...,"소소한 일상, 큰 행복",20260413,https://blog.naver.com/qiael347/224250142442,2026-06-04T11:20:17.437552
996,아키클래식,"나이키 운동화, 스타일과 편안함을 모두 갖춘 완벽한 선택",브랜드: <b>아키클래식</b> 운동화를 고를 때 중요한 점은 편안함과 스타일이겠죠...,candydiz님의 블로그,20260413,https://blog.naver.com/candydiz/224250135960,2026-06-04T11:20:17.437552
997,아키클래식,"89,000원 가격대, <b>아키클래식</b> 운동화의 성능과 효율 분석","브랜드: <b>아키클래식</b> 운동화를 고를 때 비교할 요소가 많죠. 디자인, 가...",g3credit님의 블로그,20260413,https://blog.naver.com/g3credit/224250099757,2026-06-04T11:20:17.437552
998,아키클래식,"발 편한 나이키 운동화, <b>아키클래식</b> 신상 비교 분석","브랜드: <b>아키클래식</b> 안녕하세요, 요즘 운동화 찾는 분들 많죠. 운동이나...",ogmixed님의 블로그,20260413,https://blog.naver.com/ogmixed/224250094753,2026-06-04T11:20:17.437552
999,아키클래식,"남녀 공용, 키높이와 충격흡수까지 <b>아키클래식</b> 운동화 효율 분석",브랜드: <b>아키클래식</b> 최근 운동화 선택을 놓고 비교하는 일이 잦아졌어요....,소소한 일상 이야기,20260413,https://blog.naver.com/hnjnmzl742/224250093570,2026-06-04T11:20:17.437552

In [13]:
nd = pd.read_parquet(r"D:\Desktop\AkiiiMonitor\data\raw\naver_datalab\naver_datalab_20260604.parquet")
nd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1800 entries, 0 to 1799
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   period         1800 non-null   object
 1   keyword_group  1800 non-null   object
 2   axis           1800 non-null   object
 3   ratio          1800 non-null   float64
 4   collected_at   1800 non-null   object
dtypes: float64(1), object(4)
memory usage: 70.4+ KB

In [21]:
nd.head(3)

       period keyword_group    axis     ratio                collected_at
0  2022-12-26         아키클래식  direct  44.68168  2026-06-04T11:20:15.858549
1  2023-01-02         아키클래식  direct  41.35908  2026-06-04T11:20:15.858549
2  2023-01-09         아키클래식  direct  39.62088  2026-06-04T11:20:15.858549

In [22]:
ns = pd.read_parquet(r"D:\Desktop\AkiiiMonitor\data\raw\naver_shopping\naver_shopping_20260604.parquet")
ns.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2055 entries, 0 to 2054
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   period        2055 non-null   object
 1   keyword       2055 non-null   object
 2   gender        2055 non-null   object
 3   age           2055 non-null   object
 4   ratio         2055 non-null   float64
 5   collected_at  2055 non-null   object
dtypes: float64(1), object(5)
memory usage: 96.5+ KB

In [23]:
ns.head(3)

       period keyword gender  age     ratio                collected_at
0  2022-12-26   아키클래식    all  all  71.35896  2026-06-04T11:20:30.873539
1  2023-01-02   아키클래식    all  all  63.77910  2026-06-04T11:20:30.873539
2  2023-01-09   아키클래식    all  all  55.87439  2026-06-04T11:20:30.873539

In [15]:
from collectors.naver_shopping import NaverShoppingCollector
import json

collector = NaverShoppingCollector(
        client_id="EGs26hVdRpcDBQxdTT80",
        client_secret="5PIziAaWiC",
    )

raw = collector.fetch_keyword_trend(
    category="50000167",
    keywords=[{"name": "아키클래식", "param": ["아키클래식"]}],
    gender="f",
    time_unit="week",
)
print(json.dumps(raw, ensure_ascii=False, indent=2))

TypeError: NaverShoppingCollector.fetch_keyword_trend() got an unexpected keyword argument 'keywords'. Did you mean 'keyword'?

In [14]:
# param 여러 개 테스트
response = requests.post(
    "https://openapi.naver.com/v1/datalab/shopping/category/keywords",
    headers=headers,
    data=json.dumps({
        "startDate": "2023-01-01",
        "endDate": "2026-06-03",
        "timeUnit": "week",
        "category": "50000167",
        "keyword": [
            {"name": "여행시그널", "param": ["여행 운동화", "여행운동화", "여행용 운동화"]},
        ],
        "device": "",
        "gender": "",
        "ages": []
    }, ensure_ascii=False).encode('utf-8')
)
print(response.status_code)
print(json.dumps(response.json(), ensure_ascii=False, indent=2))

400
{
  "errMsg": "TypeError: .keyword[0].param -> should NOT have more than 1 items",
  "errId": "2026-06-03T13:54:04+09:00/479326731-879639852",
  "body": "{\"startDate\":\"2023-01-01\",\"endDate\":\"2026-06-03\",\"timeUnit\":\"week\",\"category\":\"50000167\",\"keyword\":[{\"name\":\"여행시그널\",\"param\":[\"여행 운동화\",\"여행운동화\",\"여행용 운동화\"]}],\"device\":\"\",\"gender\":\"\",\"ages\":[]}"
}

In [15]:
response = requests.post(
    "https://openapi.naver.com/v1/datalab/shopping/category/keywords",
    headers=headers,
    data=json.dumps({
        "startDate": "2023-01-01",
        "endDate": "2026-06-03",
        "timeUnit": "week",
        "category": "50000167",
        "keyword": [
            {"name": "여행시그널", "param": ["여행 운동화"]},
            {"name": "발건강시그널", "param": ["족저근막염"]},
        ],
        "device": "",
        "gender": "",
        "ages": []
    }, ensure_ascii=False).encode('utf-8')
)
print(response.status_code)
print(json.dumps(response.json(), ensure_ascii=False, indent=2))

200
{
  "startDate": "2022-12-26",
  "endDate": "2026-06-03",
  "timeUnit": "week",
  "results": [
    {
      "title": "여행시그널",
      "keyword": [
        "여행운동화"
      ],
      "data": [
        {
          "period": "2023-12-11",
          "ratio": 100
        }
      ]
    },
    {
      "title": "발건강시그널",
      "keyword": [
        "족저근막염"
      ],
      "data": [
        {
          "period": "2024-12-02",
          "ratio": 100
        }
      ]
    }
  ]
}

In [12]:
import requests
import json

headers = {
    "X-Naver-Client-Id": "EGs26hVdRpcDBQxdTT80",
    "X-Naver-Client-Secret": "5PIziAaWiC",
    "Content-Type": "application/json",
}

# market 그룹 4개 한번에 테스트
response = requests.post(
    "https://openapi.naver.com/v1/datalab/shopping/category/keywords",
    headers=headers,
    json={
        "startDate": "2023-01-01",
        "endDate": "2026-06-03",
        "timeUnit": "week",
        "category": "50000167",
        "keyword": [
            {"name": "아키클래식", "param": ["아키클래식", "AKIII", "AKIII CLASSIC", "아키 클래식"]},
            {"name": "컴포트수요지수", "param": ["편한 운동화", "발 편한 신발", "편한 신발", "컴포트화", "워킹화", "경량 운동화"]},
            {"name": "여행시그널", "param": ["여행 운동화", "여행운동화", "여행용 운동화", "트레킹화", "트래킹화"]},
            {"name": "발건강시그널", "param": ["족저근막염 운동화", "족저근막 운동화", "족저근막염 신발", "아치서포트", "발건강 운동화", "발 건강 신발"]},
        ],
        "device": "",
        "gender": "",
        "ages": []
    }
)

print(response.status_code)
print(json.dumps(response.json(), ensure_ascii=False, indent=2))

400
{
  "errMsg": "TypeError: .keyword[0].param -> should NOT have more than 1 items",
  "errId": "2026-06-03T11:10:14+09:00/896224660-134994346",
  "body": "{\"startDate\":\"2023-01-01\",\"endDate\":\"2026-06-03\",\"timeUnit\":\"week\",\"category\":\"50000167\",\"keyword\":[{\"name\":\"아키클래식\",\"param\":[\"아키클래식\",\"AKIII\",\"AKIII CLASSIC\",\"아키 클래식\"]},{\"name\":\"컴포트수요지수\",\"param\":[\"편한 운동화\",\"발 편한 신발\",\"편한 신발\",\"컴포트화\",\"워킹화\",\"경량 운동화\"]},{\"name\":\"여행시그널\",\"param\":[\"여행 운동화\",\"여행운동화\",\"여행용 운동화\",\"트레킹화\",\"트래킹화\"]},{\"name\":\"발건강시그널\",\"param\":[\"족저근막염 운동화\",\"족저근막 운동화\",\"족저근막염 신발\",\"아치서포트\",\"발건강 운동화\",\"발 건강 신발\"]}],\"device\":\"\",\"gender\":\"\",\"ages\":[]}"
}

In [24]:
import json
import requests

headers = {
    "X-Naver-Client-Id": "EGs26hVdRpcDBQxdTT80",
    "X-Naver-Client-Secret": "EungL3NP4G",
    "Content-Type": "application/json",
}

# 카테고리 없이 버켄스탁만 조회
response = requests.post(
    "https://openapi.naver.com/v1/datalab/shopping/category/keywords",
    headers=headers,
    json={
        "startDate": "2025-06-01",
        "endDate": "2026-06-01",
        "timeUnit": "week",
        "category": "50000000",  # 패션의류 상위 카테고리
        "keyword": [
            {"name": "버켄스탁", "param": ["버켄스탁"]},
            {"name": "크록스", "param": ["크록스"]},
        ],
        "device": "",
        "gender": "",
        "ages": []
    }
)
print(json.dumps(response.json(), ensure_ascii=False, indent=2))

{
  "errorMessage": "NID AUTH Result Invalid (28) : Authentication failed. (인증에 실패했습니다.)",
  "errorCode": "024"
}

In [11]:
from pytrends.request import TrendReq
import json

pytrends = TrendReq(hl='ko', tz=540)  # 한국 시간대

pytrends.build_payload(
    kw_list=["아키클래식", "버켄스탁", "크록스"],
    timeframe="today 12-m",  # 최근 1년
    geo="KR"  # 한국
)

df = pytrends.interest_over_time()
print(df)

            아키클래식  버켄스탁  크록스  isPartial
date
2025-06-01      0    16   69      False
2025-06-08      0    15   82      False
2025-06-15      0    14   85      False
2025-06-22      3    16   79      False
2025-06-29      0    10   79      False
2025-07-06      4    13  100      False
2025-07-13      0    13   99      False
2025-07-20      4    13   92      False
2025-07-27      0    10   95      False
2025-08-03      0    12   84      False
2025-08-10      0    12   66      False
2025-08-17      4     6   65      False
2025-08-24      0     8   64      False
2025-08-31      0     6   59      False
2025-09-07      0     8   51      False
2025-09-14      0     9   48      False
2025-09-21      3     9   52      False
2025-09-28      5    10   41      False
2025-10-05      0     6   43      False
2025-10-12      0     7   48      False
2025-10-19      0     6   48      False
2025-10-26      5     6   40      False
2025-11-02      3     7   38      False
2025-11-09      6     6   42      False
2025-11-16      6     4   54      False
2025-11-23      0     7   43      False
2025-11-30      0     6   49      False
2025-12-07      5     5   41      False
2025-12-14      0     4   37      False
2025-12-21      4     5   41      False
2025-12-28      0     5   35      False
2026-01-04     12     7   32      False
2026-01-11      8     7   26      False
2026-01-18      6     6   33      False
2026-01-25      4     4   33      False
2026-02-01      5     6   30      False
2026-02-08      4     0   28      False
2026-02-15      4     7   34      False
2026-02-22      4     6   40      False
2026-03-01      5     8   44      False
2026-03-08      5     7   40      False
2026-03-15      6     7   41      False
2026-03-22      4     9   40      False
2026-03-29      6     7   45      False
2026-04-05      5     6   43      False
2026-04-12      0     9   49      False
2026-04-19      6     9   53      False
2026-04-26      4     8   52      False
2026-05-03      4     8   63      False
2026-05-10      4     8   59      False
2026-05-17      3    13   67      False
2026-05-24      3    11   66      False
2026-05-31      3    17   74       True

c:\Users\ugc05\AppData\Local\Programs\Python\Python313\Lib\site-packages\pytrends\request.py:260: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.fillna(False)

In [3]:
import os
import pandas as pd
from naver_datalab import NaverDataLabCollector

collector = NaverDataLabCollector(
    client_id="EGs26hVdRpcDBQxdTT80",
    client_secret="EungL3NP4G",
)

raw = collector.fetch_archi_vs_market()
rows = collector.parse_to_rows(raw)

df = pd.DataFrame(rows)
df["period"] = pd.to_datetime(df["period"])
df = df.sort_values("period")

df

        period keyword_group     ratio                collected_at
0   2025-06-02         아키클래식   5.94992  2026-06-02T10:42:40.951255
53  2025-06-02        컴포트화시장   3.38120  2026-06-02T10:42:40.951255
106 2025-06-02         경쟁브랜드  86.76186  2026-06-02T10:42:40.951255
1   2025-06-09         아키클래식   6.00544  2026-06-02T10:42:40.951255
54  2025-06-09        컴포트화시장   3.61476  2026-06-02T10:42:40.951255
..         ...           ...       ...                         ...
51  2026-05-25         아키클래식   4.96930  2026-06-02T10:42:40.951255
104 2026-05-25        컴포트화시장   3.08539  2026-06-02T10:42:40.951255
105 2026-06-01        컴포트화시장   0.48654  2026-06-02T10:42:40.951255
52  2026-06-01         아키클래식   0.75063  2026-06-02T10:42:40.951255
158 2026-06-01         경쟁브랜드  11.39348  2026-06-02T10:42:40.951255

[159 rows x 4 columns]

In [1]:
import sys
sys.path.append(r"D:\Desktop\AkiiiMonitor\collectors")

import json
import requests
from naver_search import NaverSearchCollector

collector = NaverSearchCollector(
    client_id="EGs26hVdRpcDBQxdTT80",
    client_secret="5PIziAaWiC",
)

URLS = {
    "블로그": "https://openapi.naver.com/v1/search/blog.json",
    "뉴스":   "https://openapi.naver.com/v1/search/news.json",
    "카페":   "https://openapi.naver.com/v1/search/cafearticle.json",
}

for name, url in URLS.items():
    response = requests.get(
        url,
        headers=collector.headers,
        params={"query": '"아키클래식"', "display": 3, "sort": "date"}
    )
    print(f"\n{'='*20} {name} {'='*20}")
    print(json.dumps(response.json(), ensure_ascii=False, indent=2))

==================== 블로그 ====================
{
  "lastBuildDate": "Thu, 04 Jun 2026 10:47:48 +0900",
  "total": 13117,
  "start": 1,
  "display": 3,
  "items": [
    {
      "title": "<b>아키클래식</b> 성수점 썸머 블랙프라이데이 프로모션 안내",
      "link": "https://blog.naver.com/akiiiclassic_seongsu/224304646334",
      "description": "2026.06.04 ~ 2026.06.18 &lt; 2026 SUMMER BLACK FRIDAY &gt; &lt; 썸머 블랙프라이데이 쿠폰 &gt; - 7만원 이상 구매 시 15,000원 할인 - 12만원 이상 구매 시 25,000원 할인 - 15만원 이상 구매 시 30,000원 할인 - 20만원... ",
      "bloggername": "아키클래식 성수점",
      "bloggerlink": "blog.naver.com/akiiiclassic_seongsu",
      "postdate": "20260604"
    },
    {
      "title": "데일리 아이템 방한부츠 아미뉴 남성 초경량 방한 부츠 털... ",
      "link": "https://blog.naver.com/gp6ffzmco47/224305437439",
      "description": "<b>아키클래식</b> 여성용 에스텔라 리커버리 패딩 부츠 AKAOWWH01 고객들 사이에서 입증된 만족도와 인기 다른... 4.<b>아키클래식</b> 여성용 에스텔라 리커버리 패딩 부츠 AKAOWWH01 ￦ 71,900원 별점 : ⭐⭐⭐⭐⭐ 5. 자카르타... ",
      "bloggername": "gp6ffzmco47님의 블로그",
      "bloggerlink": "blog.naver.com/gp6ffzmco47",
      "postdate": "20260604"
    },
    {
      "title": "<b>아키클래식</b> 여자 운동화 후기 쿠션 착화감 발편한 데일리 신발... ",
      "link": "https://blog.naver.com/happypanchok/224305032413",
      "description": "<b>아키클래식</b> 여자 운동화 후기 쿠션 착화감 발편한 데일리 신발 추천 신발 하나 바꿨을 뿐인데 하루가... 반복됐었는데, <b>아키클래식</b> 범퍼 운동화로 바꾸고 나서 그 불편함이 확실히 줄었습니다. 여자 운동화로... ",
      "bloggername": "애드공감",
      "bloggerlink": "blog.naver.com/happypanchok",
      "postdate": "20260604"
    }
  ]
}

==================== 뉴스 ====================
{
  "lastBuildDate": "Thu, 04 Jun 2026 10:47:48 +0900",
  "total": 4398,
  "start": 1,
  "display": 3,
  "items": [
    {
      "title": "<b>아키클래식</b>, '썸머 블랙프라이데이’ 진행",
      "originallink": "http://www.apparelnews.co.kr/news/news_view/?idx=225607",
      "link": "http://www.apparelnews.co.kr/news/news_view/?idx=225607",
      "description": "올위메이크이즈(대표 남수안)의 라이프스타일 스포츠 브랜드 ‘<b>아키클래식</b>’이 본격적인 여름 시즌을 맞아 오는 6월 4일부터 2주간 파격적인 혜택을 제공하는 ‘썸블프(썸머블랙프라이데이)’ 프로모션을 진행한다.... ",
      "pubDate": "Thu, 04 Jun 2026 09:38:00 +0900"
    },
    {
      "title": "<b>아키클래식</b>, 중국 ‘티몰 글로벌’ 입점",
      "originallink": "http://www.apparelnews.co.kr/news/news_view/?idx=225367",
      "link": "http://www.apparelnews.co.kr/news/news_view/?idx=225367",
      "description": "올위메이크이즈(대표 남수안)의 라이프스타일 스포츠 브랜드 ‘<b>아키클래식</b>’이 중국 최대 상거래 기업 알리바바 그룹의 ‘티몰 글로벌’에 공식 스토어를 오픈하고 중화권 영토 확장에 나선다. <b>아키클래식</b>은 이미 올해... ",
      "pubDate": "Wed, 20 May 2026 14:28:00 +0900"
    },
    {
      "title": "<b>아키클래식</b>, 북성수 매장 월 매출 1억 달성",
      "originallink": "http://www.apparelnews.co.kr/news/news_view/?idx=225105",
      "link": "http://www.apparelnews.co.kr/news/news_view/?idx=225105",
      "description": "올위메이크이즈(대표 남수안)의 라이프스타일 스포츠 브랜드 <b>아키클래식</b>이 성수동 오프라인 매장에서 의미 있는 성과를 만들어냈다. <b>아키클래식</b>은 성수동 북측, 이른바 ‘북성수’에 위치한 매장에서 월 매출 1억 원을... ",
      "pubDate": "Thu, 07 May 2026 14:10:00 +0900"
    }
  ]
}

==================== 카페 ====================
{
  "lastBuildDate": "Thu, 04 Jun 2026 10:47:48 +0900",
  "total": 7165,
  "start": 1,
  "display": 3,
  "items": [
    {
      "title": "<b>아키클래식</b> 아치-핏 폼 플립플랍 <b>아키클래식</b> 여성 신발 후기",
      "link": "http://cafe.naver.com/gjsdlf1234/770",
      "description": "<b>아키클래식</b> 아치-핏 폼 플립플랍 <b>아키클래식</b> 여성 신발 후기 <b>아키클래식</b> 아치-핏 폼 플립플랍을 살펴보니 편안함이 눈에 띄어요. <b>아키클래식</b> 여성 신발 후기 기준에서는 실제 사용 상황과 관리 편의성을 함께 확인하는... ",
      "cafename": "작가모임♡",
      "cafeurl": "https://cafe.naver.com/gjsdlf1234"
    },
    {
      "title": "<b>아키클래식</b> 부메랑 키높이 운동화 230사이즈 새제품",
      "link": "http://cafe.naver.com/joonggonara/1130264252",
      "description": "7 장 이미지 더보기 〉 상품 정보 <b>아키클래식</b> 부메랑 키높이 운동화 230사이즈 새제품 35,000원 시세조회 결제 혜택 N - 상품 상태 새상품, 구성품 전체 거래 방법 직거래, 택배거래 거래 희망지역 연수2동 판매자 정보... ",
      "cafename": "중고나라",
      "cafeurl": "https://cafe.naver.com/joonggonara"
    },
    {
      "title": "운동화 245",
      "link": "http://cafe.naver.com/joonggonara/1130261765",
      "description": "상세 <b>아키클래식</b> 등산화/트레킹화입니다. 신상이라 디자인도 너무 예쁘고, 트레킹할때 신으면 착화감도 엄청 좋을 것 같아요. 사이즈 좀 작아서 실착 2회후 판매합니다 260~265추천 평소에 운동화로 활용해도 예쁠... ",
      "cafename": "중고나라",
      "cafeurl": "https://cafe.naver.com/joonggonara"
    }
  ]
}

In [2]:
KEYWORDS = ["아키클래식", "포즈간츠", "23.65"]

URLS = {
    "블로그": "https://openapi.naver.com/v1/search/blog.json",
    "뉴스":   "https://openapi.naver.com/v1/search/news.json",
    "카페":   "https://openapi.naver.com/v1/search/cafearticle.json",
}

for name, url in URLS.items():
    print(f"\n{'='*20} {name} {'='*20}")
    response = requests.get(
        url,
        headers=collector.headers,
        params={"query": '"아키클래식"', "display": 2, "sort": "date"}
    )
    print(json.dumps(response.json(), ensure_ascii=False, indent=2))

==================== 블로그 ====================
{
  "lastBuildDate": "Thu, 04 Jun 2026 10:47:53 +0900",
  "total": 13117,
  "start": 1,
  "display": 2,
  "items": [
    {
      "title": "<b>아키클래식</b> 성수점 썸머 블랙프라이데이 프로모션 안내",
      "link": "https://blog.naver.com/akiiiclassic_seongsu/224304646334",
      "description": "2026.06.04 ~ 2026.06.18 &lt; 2026 SUMMER BLACK FRIDAY &gt; &lt; 썸머 블랙프라이데이 쿠폰 &gt; - 7만원 이상 구매 시 15,000원 할인 - 12만원 이상 구매 시 25,000원 할인 - 15만원 이상 구매 시 30,000원 할인 - 20만원... ",
      "bloggername": "아키클래식 성수점",
      "bloggerlink": "blog.naver.com/akiiiclassic_seongsu",
      "postdate": "20260604"
    },
    {
      "title": "데일리 아이템 방한부츠 아미뉴 남성 초경량 방한 부츠 털... ",
      "link": "https://blog.naver.com/gp6ffzmco47/224305437439",
      "description": "<b>아키클래식</b> 여성용 에스텔라 리커버리 패딩 부츠 AKAOWWH01 고객들 사이에서 입증된 만족도와 인기 다른... 4.<b>아키클래식</b> 여성용 에스텔라 리커버리 패딩 부츠 AKAOWWH01 ￦ 71,900원 별점 : ⭐⭐⭐⭐⭐ 5. 자카르타... ",
      "bloggername": "gp6ffzmco47님의 블로그",
      "bloggerlink": "blog.naver.com/gp6ffzmco47",
      "postdate": "20260604"
    }
  ]
}

==================== 뉴스 ====================
{
  "lastBuildDate": "Thu, 04 Jun 2026 10:47:53 +0900",
  "total": 4398,
  "start": 1,
  "display": 2,
  "items": [
    {
      "title": "<b>아키클래식</b>, '썸머 블랙프라이데이’ 진행",
      "originallink": "http://www.apparelnews.co.kr/news/news_view/?idx=225607",
      "link": "http://www.apparelnews.co.kr/news/news_view/?idx=225607",
      "description": "올위메이크이즈(대표 남수안)의 라이프스타일 스포츠 브랜드 ‘<b>아키클래식</b>’이 본격적인 여름 시즌을 맞아 오는 6월 4일부터 2주간 파격적인 혜택을 제공하는 ‘썸블프(썸머블랙프라이데이)’ 프로모션을 진행한다.... ",
      "pubDate": "Thu, 04 Jun 2026 09:38:00 +0900"
    },
    {
      "title": "<b>아키클래식</b>, 중국 ‘티몰 글로벌’ 입점",
      "originallink": "http://www.apparelnews.co.kr/news/news_view/?idx=225367",
      "link": "http://www.apparelnews.co.kr/news/news_view/?idx=225367",
      "description": "올위메이크이즈(대표 남수안)의 라이프스타일 스포츠 브랜드 ‘<b>아키클래식</b>’이 중국 최대 상거래 기업 알리바바 그룹의 ‘티몰 글로벌’에 공식 스토어를 오픈하고 중화권 영토 확장에 나선다. <b>아키클래식</b>은 이미 올해... ",
      "pubDate": "Wed, 20 May 2026 14:28:00 +0900"
    }
  ]
}

==================== 카페 ====================
{
  "lastBuildDate": "Thu, 04 Jun 2026 10:47:53 +0900",
  "total": 7165,
  "start": 1,
  "display": 2,
  "items": [
    {
      "title": "<b>아키클래식</b> 아치-핏 폼 플립플랍 <b>아키클래식</b> 여성 신발 후기",
      "link": "http://cafe.naver.com/gjsdlf1234/770",
      "description": "<b>아키클래식</b> 아치-핏 폼 플립플랍 <b>아키클래식</b> 여성 신발 후기 <b>아키클래식</b> 아치-핏 폼 플립플랍을 살펴보니 편안함이 눈에 띄어요. <b>아키클래식</b> 여성 신발 후기 기준에서는 실제 사용 상황과 관리 편의성을 함께 확인하는... ",
      "cafename": "작가모임♡",
      "cafeurl": "https://cafe.naver.com/gjsdlf1234"
    },
    {
      "title": "<b>아키클래식</b> 부메랑 키높이 운동화 230사이즈 새제품",
      "link": "http://cafe.naver.com/joonggonara/1130264252",
      "description": "7 장 이미지 더보기 〉 상품 정보 <b>아키클래식</b> 부메랑 키높이 운동화 230사이즈 새제품 35,000원 시세조회 결제 혜택 N - 상품 상태 새상품, 구성품 전체 거래 방법 직거래, 택배거래 거래 희망지역 연수2동 판매자 정보... ",
      "cafename": "중고나라",
      "cafeurl": "https://cafe.naver.com/joonggonara"
    }
  ]
}